version: "2"
services:
  nginx-proxy:
    restart: always
    image: nginx
    ports:
        - 8080:8080
        - 9080:8181
        - 443:443
        - 80:80
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    links:
      - dashboard:dashboard
      - cadvisor:cadvisor
      
  cadvisor:
    restart: always
    image: google/cadvisor:latest
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
  
  dashboard:
    restart: always
    image: helloworld:latest
    build: .
    ports:
      - 4200:80
